### ISSUE TITLE
Redundant macro error

### ISSUE THREAD

**Issue by RTimothyEdwards** [YosysHQ/padring#3] opened 2019-05-30 16:09 UTC
I inadvertently had an I/O cell LEF file in the wrong place and my script ended up passing the same file twice to padring.  This showed up two problems:

(1) (easy to diagnose) When encountering a redundant cell, I get the message "Cell <name> already in database -- replaced".  However, <name> is a bunch of random characters, suggesting that it is missing the variable to print, or is pointing to a freed area of memory.

(2) When I read the standard cell macro LEF file twice, I got a bad output from padring.  One of the redundantly-defined cells ended up in the output DEF file with the PLACED y coordinate as some huge number, -3.0295537569652e+33.  This suggests that when a macro is replaced, something is left uninitialized, or not quite right.

I can debug either problem if you need me to;  right now I am working on correcting and testing the GUI script.

---Tim

**Comment by trcwm** [comment] 2019-12-18 01:11
Both (1) and (2) should be fixed now. This root cause of (2) was a database corruption when cells were replaced.

**Closed as completed** 2023-05-17 15:09 UTC
Labels: bug
